### ISSUE TITLE
Unable to build for Fedora 23 on a Fusion VMWare VM

### ISSUE THREAD

**Issue by kechan** [FedoraSwift/fedora-swift#1]
I have a brand new VM with Fedora 23, using VMWare Fusion on a Mac. 

In addition to your script, I also need to install the python-devel. After patching the lib64/lib for python, the build eventually run into errors with no install package being built.

---

Testing Time: 1899.72s

---

Failing Tests (1):
    Swift :: stdlib/FloatingPointConversionTraps.swift.gyb

  Expected Passes    : 6968
  Expected Failures  : 100
  Unsupported Tests  : 623
  Unexpected Failures: 1
**\* Failed while running tests for swift (check-swift-all-linux-x86_64)
utils/build-script: command terminated with a non-zero exit status 1, aborting
utils/build-script: command terminated with a non-zero exit status 1, aborting

I plan to run "utils/build-script -t" separately to see if there are any diagnostic why the thing aborted.

**Comment by kechan** [comment]
[1056/1922] Linking CXX shared library lib/libLTO.so
FAILED: : && /usr/bin/clang++  -fPIC -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -fcolor-diagnostics -g  -Wl,-z,defs    -Wl,--version-script,/home/kelvinchan/tmp/swiftbuild/build/Ninja-DebugAssert/llvm-linux-x86_64/tools/lto/LTO.exports -shared -Wl,-soname,libLTO.so -o lib/libLTO.so tools/lto/CMakeFiles/LTO.dir/LTODisassembler.cpp.o tools/lto/CMakeFiles/LTO.dir/lto.cpp.o  lib/libLLVMX86CodeGen.a lib/libLLVMX86AsmPrinter.a lib/libLLVMX86AsmParser.a lib/libLLVMX86Desc.a lib/libLLVMX86Info.a lib/libLLVMX86Disassembler.a lib/libLLVMARMCodeGen.a lib/libLLVMARMAsmPrinter.a lib/libLLVMARMAsmParser.a lib/libLLVMARMDesc.a lib/libLLVMARMInfo.a lib/libLLVMARMDisassembler.a lib/libLLVMAArch64CodeGen.a lib/libLLVMAArch64AsmPrinter.a lib/libLLVMAArch64AsmParser.a lib/libLLVMAArch64Desc.a lib/libLLVMAArch64Info.a lib/libLLVMAArch64Disassembler.a lib/libLLVMCore.a lib/libLLVMLTO.a lib/libLLVMMC.a lib/libLLVMMCDisassembler.a lib/libLLVMSupport.a lib/libLLVMTarget.a lib/libLLVMX86CodeGen.a lib/libLLVMX86Desc.a lib/libLLVMX86AsmPrinter.a lib/libLLVMX86Utils.a lib/libLLVMX86Info.a lib/libLLVMARMDesc.a lib/libLLVMARMAsmPrinter.a lib/libLLVMARMInfo.a lib/libLLVMAsmPrinter.a lib/libLLVMSelectionDAG.a lib/libLLVMAArch64Desc.a lib/libLLVMAArch64AsmPrinter.a lib/libLLVMAArch64Info.a lib/libLLVMMCDisassembler.a lib/libLLVMAArch64Utils.a lib/libLLVMCodeGen.a lib/libLLVMTarget.a lib/libLLVMInstrumentation.a lib/libLLVMBitWriter.a lib/libLLVMLinker.a lib/libLLVMObjCARCOpts.a lib/libLLVMipo.a lib/libLLVMScalarOpts.a lib/libLLVMInstCombine.a lib/libLLVMProfileData.a lib/libLLVMObject.a lib/libLLVMMCParser.a lib/libLLVMMC.a lib/libLLVMBitReader.a lib/libLLVMVectorize.a lib/libLLVMTransformUtils.a lib/libLLVMAnalysis.a lib/libLLVMCore.a lib/libLLVMSupport.a -lrt -ldl -ltinfo -lpthread -lz -lm -Wl,-rpath,"\$ORIGIN/../lib" && :
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)

I suspect this clang got killed on linking because of memory. Will need to set higher memory for VM and retry...

**Comment by thawkins** [comment]
I found that the main swift build script does not always pass the number of  threads to all sub components.  So some steps in the build may be using  the default for ninja which i have found to be very stressfull for low resource systems. I can successfully build on a machine with an 4core/4hyperthread  processor and 12g of ram. 

It should be noted that my script is pulling the master branch, which is often broken,  i usualy wait 12 hours after it fails, update and run it again.  Once they get to a stable tag on 2.2 i will switch it to that one.

**Comment by kechan** [comment]
I reconfigured my fedora VM to a modest 4gb ram and 2 core, and it apparently further built without any "obvious" errors. I see there's a ~/tmp/swiftbuild/package/wift-linux-x86_64-fedora-2015-12-25--22:50:24.tgz and a usr/bin/swift. I will test and play with it. Thanks a whole lot putting this together. I would also like to try the package/tar other "fedora-like" dist.

**Comment by kechan** [comment]
Note: From a brand new VM from Fusion, I will need to yum install python-devel, as well as edit the script at the lines concerning git and change to:

```
https://github.com/apple/swift.git swift
etc.
etc.
```

**Comment by thawkins** [comment]
I will update the script for the python-devel  dependancy, if you get it to compile on other redhat/centos/fedora distros then letme know and i will add it to the readme, i have only really tested it on fedora 22 and fedora 23.

**Comment by thawkins** [comment]
All your changes have been incorporated, plus I have managed to eliminate the need to run the "patch" process by symlinking the directories needed to be patched before the build.
