### ISSUE TITLE
[Q] Assistance with compiling on CentOS7

### ISSUE THREAD

**Issue by SuperManifolds** [FedoraSwift/fedora-swift#3]
Good day, I am trying this solution of yours on CentOS 7 which should not be drastically different, and I am encountering this error in the build stage:

```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
```

Latest CMake and Make is already installed, I realise this is not a bug on your side, but  I was wondering if you might know what could cause this

**Comment by thawkins** [comment]
Did you run  ./swiftbuild.sh setup?

It should have installed ninja.

**Comment by SuperManifolds** [comment]
Ah, seems I failed to notice an error in the setup process

``````  
No package ninja-build available.
``` 
``````

**Comment by thawkins** [comment]
Ok,  i will look and see if i can setup a centos 7 vm and give this a try,
i should probaly have a way for installing ninja-build seperatly if its not
available.

**Comment by SuperManifolds** [comment]
Thank you, I greatily appriciate your assistance and effort in making this possible.  
I'm really not a fan of Ubuntu

**Comment by rbukovansky** [comment]
CentOS 7 script is in progress. @xlexi, please check with actual state of the project and let us know in issue if you run to anything. Thanks.
