### ISSUE TITLE
Using the Ubuntu binaries instead

### ISSUE THREAD

**Issue by Zialus** [FedoraSwift/fedora-swift#4]
The arch community seems to have figured out a way to just use the Ubuntu binaries "directly", instead of downloading the swift source code from git repositories.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=swift-development-bin

Could something like that be adapted to a script for fedora?

**Comment by thawkins** [comment]
It depends on the versions of glibc, fedora tends to be bleeding edge. Plus
there is a difference in arch/debian about how 64 bit libs are handled,
which results in a need to build specificaly for the fedora distros.

**Comment by Zialus** [comment]
I guess I'll close the issue then, it would be nice to have something that could run a bit quicker than the current script but i guess there's no alternative for now.
