### ISSUE TITLE
error install on fedora 24

### ISSUE THREAD

**Issue by hahn** [FedoraSwift/fedora-swift#6]
i try to install on fedora 24 and get error when execute swiftbuild.sh build

```
$ ./swiftbuild.sh build 
build
~/tmp/swiftbuild/swift ~/Dokumen/programfile/swift
utils/build-script: fatal error: preset file not found (tried ['/home/hahnfedora/Dokumen/programfile/swift/linuxpreset.ini'])
~/Dokumen/programfile/swift
```

how to solve this? thanks in advance :)

**Comment by hahn** [comment]
ah my bad. forget download linuxpreset.ini

sorry

**Comment by thawkins** [comment]
This script is probaly no longer relevant other than to extract the list of
build dependencies.

The swift project created thier own build driving script that now does much
of the tasks this script did for earlier versions.  And you would be better
going down that path.

**Comment by hahn** [comment]
when execute swiftbuild.sh build get error when convert swift.pod. from [1] i download again swift.pod and edit CMakeLists.txt.

when build again, error like this [2]. 

```
FAIL: Swift :: SILGen/collection_subtype_upcast.swift (1661 of 8328)
******************** TEST 'Swift :: SILGen/collection_subtype_upcast.swift' FAILED ********************
...
```

[1] http://www.kianmeng.org/2015/12/swift-in-fedora-24-rawhide.html
[2] https://gist.github.com/hahn/0cc2ab6859e9470185a72591e8ad36a8

**Comment by hahn** [comment]
oh ok. 
when i try to run swft from build/buildbot_linux/swift-linux-x86_64/bin it's still work. 

thanks for the script :)
