### ISSUE TITLE
Hi,There centos7.x installation script it?

### ISSUE THREAD

**Issue by sonwa** [FedoraSwift/fedora-swift#7]
Hi,There centos7.x installation script it?

**Comment by rbukovansky** [comment]
Hi, @sonwa, support for CentOS 7 is on its way: #11

**Comment by jeeftor** [comment]
👍

**Comment by rbukovansky** [comment]
CentOS 7 script is in progress. @jeeftor, please check with actual state of the project and let us know in issue if you run to anything. Thanks.
